package services.utils;

public enum StoreEnums {
    INVALID_UUID,
    STORE_INSERTED,
    INSERTION_FAILED,
    ITEM_INSERTION_FAILED,
    ITEM_INSERTED,
    STORE_LIST_EMPTY,
    STORE_LIST_POPULATED
}
