package services.utils;

public enum StoreEnums {
	INVALID_UUID,
	INVALID_USER,
	STORE_INSERTED,
	STORE_CREATION_FAILED_STORE_EXISTS,
	STORE_INSERTION_FAILED,
	ITEM_INSERTION_FAILED,
	ITEM_INSERTION_FAILED_PROFANITY,
	ITEM_INSERTED,
	ITEM_DELETION_FAILED,
	ITEM_DELETED,
	ITEMS_DELETED,
	ITEMS_DELETION_FAILED,
	STORE_LIST_EMPTY,
	STORE_LIST_POPULATED,
	STORE_EMPTY,
	STORE_POPULATED,
	STORE_DELETION_FAILED,
	STORE_DELETION_SUCCESSFUL,
	STORE_CREATION_FAILED_PROFANITY,
}
