package services.utils;

public enum UserEnums {
    USER_EXISTS,
    USER_AUTHORISED,
    USER_NOT_AUTHORISED,
    LOGIN_SUCCESSFUL,
    NO_SUCH_USER,
    INCORRECT_PASSWORD,
    LOGIN_FAILED,
    REGISTRATION_SUCCESSFUL,
    REGISTRATION_FAILED,
}
